---
- apt:
    name: shellcheck
  remote_user: root
  when: ansible_os_family == 'Debian' and shellcheck.source == 'debian'

- command: snap install shellcheck
  args:
    creates: /snap/bin/shellcheck
  remote_user: root
  when: ansible_os_family == 'Debian' and shellcheck.source == 'snappy'

- pacman:
    name: shellcheck
  remote_user: root
  when: ansible_distribution == 'Archlinux'

- homebrew:
    name: shellcheck
  when: ansible_system == 'Darwin'
